

# This file was *autogenerated* from the file hodgeCI.sage
from sage.all_cmdline import *   # import sage library

_sage_const_1 = Integer(1); _sage_const_0 = Integer(0); _sage_const_2 = Integer(2); _sage_const_7 = Integer(7)# hodgeCI.sage
#
# Computes the bivariate Chern-character polynomial
#   Phi_X(x, t) = sum_{p, q} h^{p, q}(X, Omega^p_X(t)) x^p t^q (mod normalizations)
# for X = Gr(k, n) via the t-hook formula on partitions in a k x m box
# (m = n - k), and for a smooth complete intersection Z = X cap V(f_1, ...)
# via repeated application of (1 - T_d) on the t variable in QQ[x][t].
#
# Phi_Gr(k, n)        -- Chern polynomial for the Grassmannian
# Phi_CI(Phi_X, degs) -- pushforward to a smooth CI of the given multidegree
#
# The trailing block exercises both functions on Gr(2, 7) and its [1]*7
# complete intersection (a CY3); the printed sanity values (Phi_X(0,0)=1,
# Phi_X(1,0)=21, Phi_Z(0,0)=2) are the expected outputs.
#
# Run with:  sage hodgeCI.sage
# See also:  hodge.m2 (the Macaulay2 analogue, more thoroughly tested).

def Phi_Gr(k, n):
    """
    Phi_X(x, t) for X = Gr(k, n), as an element of Q[x, t].
    Uses the t-hook ratio formula directly.
    """
    m = n - k
    R = PolynomialRing(QQ, ['x', 't'])
    x, t = R.gens()

    def hook(la, a, b):
        # standard hook length of partition la at cell (a, b), 1-indexed
        return la[a-_sage_const_1 ] - b + sum(_sage_const_1  for u in la if u >= b) - a + _sage_const_1 

    def ext_hook(la, a, b):
        # extended hook in the k x m bounding box
        if b <= la[a-_sage_const_1 ]:
            return hook(la, a, b)
        laC = [m - la[k-i] for i in range(_sage_const_1 , k+_sage_const_1 )]   # complement
        return -hook(laC, k+_sage_const_1 -a, m+_sage_const_1 -b)

    Phi = R.zero()
    for s in range(k*m + _sage_const_1 ):
        for la in Partitions(s, max_length=k, max_part=m):
            la = list(la) + [_sage_const_0 ]*(k - len(la))
            f = R.one()
            for a in range(_sage_const_1 , k+_sage_const_1 ):
                for b in range(_sage_const_1 , m+_sage_const_1 ):
                    h = ext_hook(la, a, b)
                    f *= (h - t) / h
            Phi += x**s * f
    return Phi

def Phi_CI(Phi_X, degrees):
    """Phi_Z(x,t) for Z ⊂ X a smooth CI of the given multidegree."""
    R = Phi_X.parent()
    x_var, t_var = R.gens()

    # Lift QQ[x,t] -> QQ[x][t]: t is the active variable, x lives in coeff ring.
    QQx = PolynomialRing(QQ, 'x'); x = QQx.gen()
    Rt  = PolynomialRing(QQx, 't'); t = Rt.gen()

    def lift(p):
        out = Rt.zero()
        for (i, j), c in p.dict().items():
            out += QQ(c) * x**i * t**j
        return out

    Phi = lift(Phi_X)

    for d in degrees:
        G = Phi - Phi(t - d)            # = (1 - T_d) Phi, in QQ[x][t]
        D = G.degree()                   # degree in t
        if D < _sage_const_0 :
            Phi = Rt.zero(); continue
        f_partial = Rt.zero()
        for k in range(D , -_sage_const_1 , -_sage_const_1 ):
            shifted = (x * f_partial)(t - d)         # in QQ[x][t]
            rhs = G[k] + shifted[k]                  # in QQ[x]
            quo, rem = rhs.quo_rem(_sage_const_1  - x)            # univariate, honest
            assert rem == _sage_const_0 , f"non-exact at t^{k}: rem = {rem}"
            f_partial += quo * t**k
        Phi = f_partial

    # Push back to QQ[x,t] for return.
    out = R.zero()
    for j in range(Phi.degree() + _sage_const_1  if Phi != _sage_const_0  else _sage_const_0 ):
        cx = Phi[j]
        for i in range(cx.degree() + _sage_const_1 ):
            out += QQ(cx[i]) * x_var**i * t_var**j
    return out

PhiX = Phi_Gr(_sage_const_2 , _sage_const_7 )
x, t = PhiX.parent().gens()
print("t-degree:", PhiX.degree(t))           # must be 10
print("Phi_X(0, 0):", PhiX.subs({x:_sage_const_0 , t:_sage_const_0 })) # must be 1
print("Phi_X(1, 0):", PhiX.subs({x:_sage_const_1 , t:_sage_const_0 })) # must be 21
print("Phi_X(0, t):")
print(PhiX.subs({x: _sage_const_0 }))                      # Hilbert poly of Gr(2,7)
print("Phi_X(x, 0):")
print(PhiX.subs({t: _sage_const_0 }))   # must be 1+x+2x^2+2x^3+3x^4+3x^5+3x^6+2x^7+2x^8+x^9+x^10

PhiZ = Phi_CI(PhiX, [_sage_const_1 ]*_sage_const_7 )
print(PhiZ.subs({t:_sage_const_0 }))         # -49*x - 49*x^2
print(PhiZ.subs({x:_sage_const_0 , t:_sage_const_0 }))    # 2  (= chi(O_Z) for a CY3)
print("Phi_Z t-degree:", PhiZ.degree(t))   # 3

