"""
Sharpness tracking for the six conjectured strengthenings of Snow's bounds.

For each conjecture, slack = RHS - LHS in the cleared-integer form.
  slack < 0  ->  conjecture fails on that instance
  slack = 0  ->  conjecture is tight (equality holds)
  slack > 0  ->  conjecture holds strictly

A "tight" instance gives strong evidence that the conjecture cannot be
strengthened further (at least for that family of parameters).
"""


# This file was *autogenerated* from the file SnowBoundConjecture.sage
from sage.all_cmdline import *   # import sage library

_sage_const_0 = Integer(0); _sage_const_2 = Integer(2); _sage_const_1 = Integer(1); _sage_const_4 = Integer(4); _sage_const_3 = Integer(3); _sage_const_5 = Integer(5); _sage_const_6 = Integer(6); _sage_const_20 = Integer(20); _sage_const_15 = Integer(15); _sage_const_7 = Integer(7)
from sage.all import Cores, Partition, flatten, isqrt
from math import inf


def is_kn_bounded(p, k, n):
    return len(p) <= k and (len(p) == _sage_const_0  or p[_sage_const_0 ] <= n - k)


def snow_partitions(t, j):
    if t < _sage_const_2 :
        if j == _sage_const_0 :
            yield Partition([]), _sage_const_0 
        return
    for c in Cores(t, size=j):
        p = c.to_partition()
        hl = flatten(p.hook_lengths())
        i = sum(_sage_const_1  for h in hl if h > t)
        yield p, i


def slacks(k, n, j, t, i):
    """Return dict: conjecture index -> slack (RHS - LHS, integer form).

    For C1-C3 the slack equals the ordinary slack (no rational clearing).
    For C4-C6 the slack is in cleared-integer form: slack = 0 iff equality
    holds in the original rational inequality.
    """
    return {
        _sage_const_1 : (t + (n - _sage_const_4 ) ** _sage_const_2  // _sage_const_4 ) - (j - i),
        _sage_const_2 : ((j - i) ** _sage_const_2 ) - ((t - _sage_const_1 ) * (j + i) - (t - _sage_const_1 ) ** _sage_const_2  // _sage_const_4 ),
        _sage_const_3 : (n - _sage_const_1  - isqrt(_sage_const_4  * i - _sage_const_3 )) - t,
        _sage_const_4 : k * (n - k) * (n - t) - _sage_const_2  * n * i,
        _sage_const_5 : k * (n - k) * (n + t) - _sage_const_2  * n * j,
        _sage_const_6 : k * (k + _sage_const_1 ) ** _sage_const_2  * (t - _sage_const_1 ) - _sage_const_2  * (k + _sage_const_1 ) * i - _sage_const_4  * j,
    }


def verify_with_sharpness(j_max=_sage_const_20 , t_max=_sage_const_20 , n_max=_sage_const_15 , max_examples=_sage_const_5 ):
    """Exhaustive verification + per-conjecture tightness tracking."""
    summary = {
        c: {'min_slack': inf, 'tight_count': _sage_const_0 , 'failures': _sage_const_0 , 'examples': []}
        for c in range(_sage_const_1 , _sage_const_7 )
    }
    total = _sage_const_0 

    for j in range(_sage_const_1 , j_max + _sage_const_1 ):
        for t in range(_sage_const_2 , t_max + _sage_const_1 ):
            for p, i in snow_partitions(t, j):
                if i == _sage_const_0 :
                    continue
                for n in range(_sage_const_4 , n_max + _sage_const_1 ):
                    for k in range(_sage_const_2 , n - _sage_const_1 ):  # 2 <= k <= n-2
                        if not is_kn_bounded(p, k, n):
                            continue
                        total += _sage_const_1 
                        sl = slacks(k, n, j, t, i)
                        for c, s in sl.items():
                            entry = summary[c]
                            if s < _sage_const_0 :
                                entry['failures'] += _sage_const_1 
                            if s < entry['min_slack']:
                                entry['min_slack'] = s
                                entry['tight_count'] = _sage_const_1 
                                entry['examples'] = [(k, n, j, t, i, tuple(p))]
                            elif s == entry['min_slack']:
                                entry['tight_count'] += _sage_const_1 
                                if len(entry['examples']) < max_examples:
                                    entry['examples'].append((k, n, j, t, i, tuple(p)))
        print(f"j={j} done")

    return summary, total


if __name__ == "__main__":
    summary, total = verify_with_sharpness(j_max=_sage_const_20 , t_max=_sage_const_20 , n_max=_sage_const_20 )
    print(f"\nTested {total} Snow partition instances.\n")
    for c in range(_sage_const_1 , _sage_const_7 ):
        entry = summary[c]
        status = "OK" if entry['failures'] == _sage_const_0  else f"FAIL ({entry['failures']} counterexamples)"
        if entry['min_slack'] == _sage_const_0 :
            sharp = "TIGHT (equality achieved)"
        elif entry['min_slack'] < _sage_const_0 :
            sharp = f"VIOLATED (min slack = {entry['min_slack']})"
        else:
            sharp = f"strict (min slack = {entry['min_slack']})"
        print(f"Conjecture {c}: {status}, {sharp}, {entry['tight_count']} witnesses at min slack")
        for ex in entry['examples'][:_sage_const_3 ]:
            k, n, j, t, i, lam = ex
            print(f"    k={k} n={n} j={j} t={t} i={i}  lambda={lam}")
        print()

